version: "3"
services:
  database:
    image: "postgres:16.4-alpine"
    container_name: "RideOrCry-DB"
    environment:
      POSTGRES_DB: ride_or_cry_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-boot:
    build:
      context: .
    container_name: "RideOrCry-SERVER"
    depends_on:
      - database
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/ride_or_cry_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    ports:
      - "8080:8080"

volumes:
  postgres_data: